# Generated by Django 4.1 on 2022-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero_Casa', models.IntegerField()),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
    ]
