# Generated by Django 4.1 on 2022-08-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('CPF', models.CharField(max_length=20)),
                ('CNPJ', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=30)),
                ('Whatsapp', models.BooleanField(default=False)),
                ('Email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cep',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cnpj',
            new_name='CNPJ',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=400)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_Solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_Execucao', models.DateField(null=True)),
                ('Status', models.CharField(max_length=30)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.vendedor')),
            ],
        ),
    ]
