# Generated by Django 4.1 on 2022-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_vendedor_rename_cep_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CNPJ',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='CNPJ',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
