# Generated by Django 4.1 on 2022-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_cnpj_alter_vendedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_Casa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='data_Execucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
