# Generated by Django 4.1 on 2022-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_cnpj_alter_cliente_numero_casa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='CPF',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
